export interface employee{
    id:number,
    name:string,
    userName:string,
    password:string,
    address:string,
    salary:number,
    gender:string,
    dob:Date,
    visitedCountry:string[],
    phone:string,
    isMareid:boolean,
    skills:string[],
    hobbies:string[],
    bloodgroup:number,
    fcolor:string,
    bio:string,
    ff:boolean,
  
  };